[settings]
ID = 'px-frontend'

[build]
publish = 'build/'
command = 'preact build --no-prerender'

[[redirects]]
  from = "/resources/*"
  to = "/resources/*"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
